language: objective-c
osx_image: xcode7.3
branches:
  only:
    - dev
script:
- if [ $MODE == 'test8' ]; then set -o pipefail && xcodebuild -workspace cdmx.xcworkspace -scheme cdmx -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=7.1,name=iPhone 4s" test | xcpretty -c; fi
- if [ $MODE == 'test9' ]; then set -o pipefail && xcodebuild -workspace cdmx.xcworkspace -scheme cdmx -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" test | xcpretty -c; fi
- if [ $MODE == 'Release' ]; then xctool -workspace cdmx.xcworkspace -scheme cdmx -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" -configuration Release build; fi
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=test8
  - MODE=test9
  - MODE=Release
