sudo: false
language: objective-c
osx_image: xcode7.3
branches:
  only:
    - dev
script:
  xctool -workspace cdmx.xcworkspace \
                              -scheme tests \
                              -sdk "iphonesimulator" \
                              -destination "platform=iOS Simulator,OS=8.1,name=iPhone 6" \
                              test \
                              -freshInstall -freshSimulator

  xctool -workspace cdmx.xcworkspace \
                              -scheme cdmx \
                              -sdk "iphonesimulator" \
                              -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" \
                              test \
                              -freshInstall -freshSimulator
notifications:
  email:
    on_success: never
    on_failure: never
