sudo: false
language: objective-c
osx_image: xcode7.3
xcode_workspace: cdmx.xcworkspace
xcode_scheme: tests
branches:
  only:
    - dev
xcode_sdk:
  - iphonesimulator9.3
notifications:
  email:
    on_success: never
    on_failure: never
