sudo: false
language: objective-c
osx_image: xcode7.3
xcode_workspace: cdmx.workspace
xcode_scheme: cdmx
branches:
  only:
    - dev
env:
  - TEST_SDK="iphonesimulator7.0" SIMULATOR="iphone"
  - TEST_SDK="iphonesimulator8.1" SIMULATOR="iphone"
  - TEST_SDK="iphonesimulator9.2" SIMULATOR="iphone"
script:
  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR
