sudo: false
language: objective-c
osx_image: xcode7.3
xcode_workspace: cdmx.workspace
xcode_scheme: cdmx
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator8.1
  - iphonesimulator9.2
branches:
  only:
  - dev
